### ISSUE TITLE
Add underblog Docker image into Docker Hub for non-Mac users

### ISSUE THREAD

**Issue by egregors** [freetonik/underblog#15]
It will be nice if we are adding the easy way to get underblog for non macOS users. I think Docker image – the best way. Popular technology, easy to implement, easy to automate uploading new versions. And it will be useful for Mac users as well when you don't wanna install underblog globally.

- [x] add Dockerfile (I may do this)
- [x] setup auto DockerHub build for every push into Master (is's free for Open Source, but only you may set it up on the DockerHub side)
- [x] update README (add an alternative way to get underblog)
- [x] (Optional) add DockerHub build status badge

**Comment by freetonik** [comment]
>I think Docker image – the best way. 

Sorry, but no way it's the best way! It supposed to be a tiny, portable binary. I'd rather install Win10 on Virtualbox and build binaries myself. 

I mean, I won't stop you from doing it and gladly add DockerHub integration you suggested, as well as add this info to FAQ as an "alternative way to get underblog", but I, with all respect, shall not encourage this as an "official way".

So, how do you want to proceed?

**Comment by egregors** [comment]
When I am talking about Docker as the "best way for non-mac users" I am mostly mean best delivery way to Linux users. 

Push some software into Brew repo looks pretty easy, but you can't just add the same in the Linux official repos. Yep, you still may download source and just make `make build`, or you may add the custom repo for apt (or another pkg manager), but all these ways still longer than just: `docker run freetonik/underblog .`

For Win users, I believe the best way – put exe in the releases. I mean exe for Windows should be build artifact (when we will get CI)

**Comment by egregors** [comment]
To enable DockerHub autobuild you should go to https://hub.docker.com/ and "Create Repository". Chose "Public", connect to GitHub and select this repo. Leave the "BUILD RULES" section as default. 

After all of that, please check out the path to the image (username/imagename) and update the README, if it will not be `freetonic/underblog`

**Comment by freetonik** [comment]
@egregors I've added the repo to dockerhub! 

>After all of that, please check out the path to the image (username/imagename) and update the README, if it will not be freetonic/underblog

Seems like it didn't change since I have the same username on both github and dockerhub (https://hub.docker.com/r/freetonik/underblog)
