### ISSUE TITLE
RSS generation

### ISSUE THREAD

**Issue by freetonik** [freetonik/underblog#28]
We need to generate RSS, or it's not really a blog :-)

**Comment by duckoder** [comment]
I'd like to work on this issue, of course if it's still actual and unoccupied 🙂

**Comment by freetonik** [comment]
It is! Go for it! :-) We're looking for the simplest implementation: unlimited-by-time, full-text RSS with no bells & whistles.

**Comment by duckoder** [comment]
Nice! 👍
I'll start work on it in a next few days!

**Comment by duckoder** [comment]
Hey @freetonik! I started to work on RSS generation logic.
I've added a new CLI argument for RSS, `-hostname` (https://github.com/zhikiri/underblog/blob/master/app/internal/cli.go#L23)

I'm a bit concerned about CLI for RSS generation, which behaviour looks more eloquent/preferred from your point of view:

**Option 1**
 - `./underblog -hostname http://example.com` - generates HTML + RSS

**Option 2**
 - `./underblog -hostname http://example.com` - generates only RSS

**Comment by freetonik** [comment]
Hey,

IMO, HTML and RSS should always be in sync, therefore there should be no option to generate one without the other.

As for hostname options: due to minimal nature of Underblog, I'd love to have as few options as possible. So, maybe there's a way to derive the hostname from elsewhere? One idea is to always specify the canonical url in `index.html` and get the hostname from there (`<link rel="canonical" href="http://example.com" />`.

What do you think?

**Comment by duckoder** [comment]
Thant's great! I think that "canonical" solution is what we're looking for :) 
I'm concerning about url setup obscurity though... 

Anyways, we could raise an error in case of missing canonical link and it  should be fine :)
Thanks 👍

**Comment by duckoder** [comment]
Hey @freetonik! 
Could you check this one https://github.com/freetonik/underblog/pull/34 ?
