### ISSUE TITLE
Date not showing up

### ISSUE THREAD

**Issue by tyeeman** [freetonik/underblog#30]
Very nice, simple, thanks for writing it! Since the date is in the filename it would be nice to have the date beside the filename in the index file. Was this an oversight? Is it easy to add the date?

**Comment by freetonik** [comment]
Hey! Thanks!

Yes, it's pretty easy to add it, definitely an oversight.

**Comment by freetonik** [comment]
Fixed by https://github.com/freetonik/underblog/commit/75a7fa8fc3af2fa2fe6b3970acbee8358bc45d84
