### ISSUE TITLE
Get request error for example blog using vs code live preview

### ISSUE THREAD

**Issue by bfmcneill** [freetonik/underblog#31]
After cloning the example blog and running the underblog command on windows I get the public file output.  When I open the public file's index.html the vscode live preview works but all the links give me a get request error.    any ideas?  I tried multiple live preview extensions and am getting the same behavior.

**Comment by freetonik** [comment]
Can you please specify what kind of request error it is and where the links point to (full url)?

**Comment by freetonik** [comment]
I may have an idea. Links generated by underblog are relative to server root. This means that if you just open `index.html` in a file system and click a link, it’ll point to something like `file:///posts/Test/`. 

I think the best solution is to use `underblog -watch` for live preview. It starts a local web server at http://localhost:8080/ and allows for seamless preview. I'd added some info to README.

Thank you.
