### ISSUE TITLE
Building for Windows

### ISSUE THREAD

**Issue by tyeeman** [freetonik/underblog#33]
Thanks for adding the date to the index page but I'm trying to build an exe for Windows and ran "go build" in the "app" folder and got a 10MB file. Is this the correct way to build?

**Comment by freetonik** [comment]
Hey,
yes. Go binaries are notoriously large. There are ways to mitigate this, to an extent, but I haven't looked into it yet.

Official binaries can be found here https://github.com/freetonik/underblog/releases
As you can see, when unzipped, they all are about 10mb.
