### ISSUE TITLE
Concurrency problem

### ISSUE THREAD

**Issue by egregors** [freetonik/underblog#7]
```
        for _, file := range files {
		if path.Ext(file.Name()) == ".md" || path.Ext(file.Name()) == ".markdown" {
			fmt.Println("Processing " + file.Name())
			post := createPost(file.Name())
			go createPostFile(post)
			posts = append(posts, post)
			fmt.Println("Done with  " + file.Name())
			fmt.Println("---")
		}
	}
```
Here you put `post` into `posts` just after runing the `createPostFile` goroutine, so you can't be sure that processing is already done, when you will try to make

```
t, _ := template.ParseFiles("index.html")
	t.Execute(f, posts)
```

In this case, you should use `channels` and `wait group` to make this code thread-safe

**Comment by freetonik** [comment]
Hey!

Line 56 in the original release is actually a bug left out after experimenting. I meant to use no goroutines altogether. I shouldn't work after 10pm :D

2 problems with concurrent `createPostFile` become relevant with large number of files/workers, for example, with 10,000 md files:

1. We hit the OS FS-access limit and fail with "Too many files" error (at least that's the case on macOS). I guess this can be solved with either rate limiting or small timeouts, but that might make concurrent version as "slow" as non-concurrent one, which would defeat the purpose while adding complexity.
2. Templating engine fails with `panic: runtime error: invalid memory address or nil pointer dereference`. I did not investigate this.

What do you think? Both problems were inconsistent, some runs yielded no errors. Such cases had showed 2x speedup on my machine (3,5 GHz Intel Core i5), I'm not sure it's worth it.

**Comment by freetonik** [comment]
Just tested your current implementation to verify both problems with 10k md files:

```
Processing 24-10-2019-Welcome8096.md
Done with  24-10-2019-Welcome8096.md
---
Processing 24-10-2019-Welcome8097.md
Done with  24-10-2019-Welcome8097.md
---
Processing 24-10-2019-Welcome8098.md
Done with  24-10-2019-Welcome8098.md
---
Processing 24-10-2019-Welcome8099.md
Done with  24-10-2019-Welcome8099.md
---
Processing 24-10-2019-Welcome81.md
Aaa!
2019/10/25 06:25:51 open ./markdown/24-10-2019-Welcome81.md: too many open files
2019/10/25 06:25:51 open public/posts/Welcome8099/index.html: too many open files
```

and

```
Processing 24-10-2019-Welcome8114.md
Done with  24-10-2019-Welcome8114.md
---
Processing 24-10-2019-Welcome8115.md
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1162ec2]

goroutine 15422 [running]:
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:95 +0x42
html/template.(*Template).Execute(0x0, 0x120cc40, 0xc00007c1b0, 0x11b5420, 0xc002070280, 0x120cc80, 0xc002309710)
	/usr/local/Cellar/go/1.13.1/libexec/src/html/template/template.go:119 +0x2f
main.createPostFile(0xc002fb8000, 0x13, 0xc002f41500, 0x9ae, 0x0, 0xed542e080, 0x0, 0xc00033d6c7, 0xb, 0xc0000b2010)
	/Users/rakhim/code/go/src/egregors_underblog/underblog.go:154 +0x2a1
created by main.main
	/Users/rakhim/code/go/src/egregors_underblog/underblog.go:64 +0x69f
```

**Comment by egregors** [comment]
I got it. In this case, we should spawn some amount of workers with the limit. Let's say we may get  File Descriptor Limit (N) by `ulimit -n`, and spawn N workers witch will be expected channel with files and will die when a channel becomes closed. So then, at any moment of time, we'll not break the `ulimit` limit but will get the most efficient way to deal with files

I'll add this case into this PR.

It will be useful, if you may upload zip with 10k md test case somewhere, or add it all like a test.

**Comment by freetonik** [comment]
Sounds good! 

Also, I think it should fail gracefully in case `ulimit` util is unavailable (like, on Windows?) and use some default limits instead.

[Here is a zip-file](https://drive.google.com/open?id=1QtK-1SWMQJdsShbXtcjj1G8J9X4Xj53H) with 10k md files. I generated them with a bash one-liner:

```bash
for f in {1..10000}; do cp file.md file$f.md; done
```

**Comment by egregors** [comment]
@freetonik  I'm made it as we plan. Current result for 10k case:
```
➜  example git:(issue7) ✗ ../underblog
Underblog 0.2
Starting...
2019/10/26 12:26:15 [DEBUG] wLimit: 128
2019/10/26 12:26:17 Done in 1.523566369s
```

**Comment by freetonik** [comment]
Reopening this: there's race condition currently cause by these in `blog.go`:

```go
	b.createPosts()
	err := b.renderMd()
```

index page is being built when `b.posts` is not necessarily populated. As a result, `index.html` contains zero links.

**Comment by egregors** [comment]
@freetonik Right, my bad. Programming after 10 pm, you know :D 
I'll make a fix tomorrow

**Comment by freetonik** [comment]
I just "fixed" it by fucking up :D

**Comment by freetonik** [comment]
Alright, this seem to be fixed now by https://github.com/freetonik/underblog/commit/61edb9001bc037702b6dcfb8a0a6cdc952ae9394
